ALTER TABLE users ADD PRIMARY KEY (id);
ALTER TABLE postTypes ADD PRIMARY KEY (id);

ALTER TABLE posts ADD PRIMARY KEY (id);
ALTER TABLE posts ADD CONSTRAINT posts_lastEditorUserId_fkey FOREIGN KEY (lastEditorUserId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE posts ADD CONSTRAINT posts_ownerUserId_fkey FOREIGN KEY (ownerUserId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE posts ADD CONSTRAINT posts_postTypeId_fkey FOREIGN KEY (postTypeId) REFERENCES postTypes (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE voteTypes ADD PRIMARY KEY (id);

ALTER TABLE votes ADD PRIMARY KEY (id);
ALTER TABLE votes ADD CONSTRAINT votes_postId_fkey FOREIGN KEY (postId) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE votes ADD CONSTRAINT votes_userId_fkey FOREIGN KEY (userId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE votes ADD  CONSTRAINT votes_voteTypeId_fkey FOREIGN KEY (voteTypeId) REFERENCES voteTypes (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE badges ADD PRIMARY KEY (id);
ALTER TABLE badges ADD CONSTRAINT badges_userId_fkey FOREIGN KEY (userId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE comments ADD PRIMARY KEY (id);
ALTER TABLE comments ADD  CONSTRAINT comments_postId_fkey FOREIGN KEY (postId) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE comments ADD  CONSTRAINT comments_userId_fkey FOREIGN KEY (userId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE postHistoryTypes ADD PRIMARY KEY (id);

ALTER TABLE postHistory ADD PRIMARY KEY (id);
ALTER TABLE postHistory ADD CONSTRAINT postHistory_postHistoryTypeId_fkey FOREIGN KEY (postHistoryTypeId) REFERENCES postHistoryTypes (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE postHistory ADD  CONSTRAINT postHistory_postId_fkey FOREIGN KEY (postId) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE postHistory ADD  CONSTRAINT postHistory_userId_fkey FOREIGN KEY (userId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tags ADD PRIMARY KEY (id);

ALTER TABLE postLinks ADD PRIMARY KEY (id);
ALTER TABLE postLinks ADD  CONSTRAINT postLinks_postId_fkey FOREIGN KEY (postId) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tags ADD CONSTRAINT tags_excerptpostid_fkey FOREIGN KEY (excerptpostid) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE tags ADD  CONSTRAINT tags_wikipostid_fkey FOREIGN KEY (wikipostid) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE dates ADD PRIMARY KEY (datekey);

ALTER TABLE badges ADD CONSTRAINT badges_pkey PRIMARY KEY (id);



