ALTER TABLE users ADD PRIMARY KEY (id);
ALTER TABLE postTypes ADD PRIMARY KEY (id);

ALTER TABLE posts ADD PRIMARY KEY (id);
ALTER TABLE posts ADD CONSTRAINT posts_lastEditorUserId_fkey FOREIGN KEY (lastEditorUserId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE posts ADD CONSTRAINT posts_ownerUserId_fkey FOREIGN KEY (ownerUserId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE posts ADD CONSTRAINT posts_postTypeId_fkey FOREIGN KEY (postTypeId) REFERENCES postTypes (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE voteTypes ADD PRIMARY KEY (id);

ALTER TABLE votes ADD PRIMARY KEY (id);
ALTER TABLE votes ADD CONSTRAINT votes_postId_fkey FOREIGN KEY (postId) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE votes ADD CONSTRAINT votes_userId_fkey FOREIGN KEY (userId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE votes ADD  CONSTRAINT votes_voteTypeId_fkey FOREIGN KEY (voteTypeId) REFERENCES voteTypes (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE badges ADD PRIMARY KEY (id);
ALTER TABLE badges ADD CONSTRAINT badges_userId_fkey FOREIGN KEY (userId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE comments ADD PRIMARY KEY (id);
ALTER TABLE comments ADD  CONSTRAINT comments_postId_fkey FOREIGN KEY (postId) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE comments ADD  CONSTRAINT comments_userId_fkey FOREIGN KEY (userId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE postHistoryTypes ADD PRIMARY KEY (id);

ALTER TABLE postHistory ADD PRIMARY KEY (id);
ALTER TABLE postHistory ADD CONSTRAINT postHistory_postHistoryTypeId_fkey FOREIGN KEY (postHistoryTypeId) REFERENCES postHistoryTypes (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE postHistory ADD  CONSTRAINT postHistory_postId_fkey FOREIGN KEY (postId) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE postHistory ADD  CONSTRAINT postHistory_userId_fkey FOREIGN KEY (userId) REFERENCES users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE tags ADD PRIMARY KEY (id);

ALTER TABLE postLinks ADD PRIMARY KEY (id);
ALTER TABLE postLinks ADD  CONSTRAINT postLinks_postId_fkey FOREIGN KEY (postId) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tags ADD CONSTRAINT tags_excerptpostid_fkey FOREIGN KEY (excerptpostid) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE tags ADD  CONSTRAINT tags_wikipostid_fkey FOREIGN KEY (wikipostid) REFERENCES posts (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE dates ADD PRIMARY KEY (datekey);

ALTER TABLE comments_dim ADD CONSTRAINT comments_dim_pkey PRIMARY KEY (id);
ALTER TABLE comments_dim ADD  CONSTRAINT comments_dim_creation_date_key_fkey FOREIGN KEY (creation_date_key) REFERENCES dates (datekey) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE badges ADD CONSTRAINT badges_pkey PRIMARY KEY (id);
ALTER TABLE badges ADD CONSTRAINT badges_userid_fkey1 FOREIGN KEY (userid) REFERENCES users_dim (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE post_dim ADD CONSTRAINT post_dim_pkey PRIMARY KEY (id);
ALTER TABLE post_dim ADD  CONSTRAINT post_dim_date_key_fkey FOREIGN KEY (date_key) REFERENCES dates (datekey) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE posthistory_dim ADD CONSTRAINT posthistory_dim_pkey PRIMARY KEY (id);
ALTER TABLE posthistory_dim ADD  CONSTRAINT posthistory_dim_creation_date_key_fkey FOREIGN KEY (creation_date_key) REFERENCES dates (datekey) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_dim ADD CONSTRAINT users_dim_pkey PRIMARY KEY (id);
ALTER TABLE users_dim ADD   CONSTRAINT users_dim_creation_date_key_fkey FOREIGN KEY (creation_date_key) REFERENCES dates (datekey) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE votes_dim ADD CONSTRAINT votes_dim_pkey PRIMARY KEY (id);
ALTER TABLE votes_dim ADD  CONSTRAINT votes_dim_post_id_fkey FOREIGN KEY (post_id) REFERENCES post_dim (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;