INSERT INTO postHistoryTypes (id, name) VALUES (1, 'Initial Title');
INSERT INTO postHistoryTypes (id, name) VALUES (2, 'Initial Body');
INSERT INTO postHistoryTypes (id, name) VALUES (3, 'Initial Tags');
INSERT INTO postHistoryTypes (id, name) VALUES (4, 'Edit Title');
INSERT INTO postHistoryTypes (id, name) VALUES (5, 'Edit Body');
INSERT INTO postHistoryTypes (id, name) VALUES (6, 'Edit Tags');
INSERT INTO postHistoryTypes (id, name) VALUES (7, 'Rollback Title');
INSERT INTO postHistoryTypes (id, name) VALUES (8, 'Rollback Body');
INSERT INTO postHistoryTypes (id, name) VALUES (9, 'Rollback Tags');
INSERT INTO postHistoryTypes (id, name) VALUES (10, 'Post Closed');
INSERT INTO postHistoryTypes (id, name) VALUES (11, 'Post Reopened ');
INSERT INTO postHistoryTypes (id, name) VALUES (12, 'Post Deleted');
INSERT INTO postHistoryTypes (id, name) VALUES (13, 'Post Undeleted ');
INSERT INTO postHistoryTypes (id, name) VALUES (14, 'Post Locked');
INSERT INTO postHistoryTypes (id, name) VALUES (15, 'Post Unlocked ');
INSERT INTO postHistoryTypes (id, name) VALUES (16, 'Community Owned');
INSERT INTO postHistoryTypes (id, name) VALUES (17, 'Post Migrated');
INSERT INTO postHistoryTypes (id, name) VALUES (18, 'Question Merged  ');
INSERT INTO postHistoryTypes (id, name) VALUES (19, 'Question Protected ');
INSERT INTO postHistoryTypes (id, name) VALUES (20, 'Question Unprotected ');
INSERT INTO postHistoryTypes (id, name) VALUES (22, 'Question Unmerged  ');
INSERT INTO postHistoryTypes (id, name) VALUES (24, 'Suggested Edit Applied');
INSERT INTO postHistoryTypes (id, name) VALUES (25, 'Post Tweeted ');
INSERT INTO postHistoryTypes (id, name) VALUES (31, 'Discussion moved to chat');
INSERT INTO postHistoryTypes (id, name) VALUES (33, 'Post Notice Added ');
INSERT INTO postHistoryTypes (id, name) VALUES (34, 'Post Notice Removed ');
INSERT INTO postHistoryTypes (id, name) VALUES (35, 'Post Migrated Away ');
INSERT INTO postHistoryTypes (id, name) VALUES (36, 'Post Migrated Here ');
INSERT INTO postHistoryTypes (id, name) VALUES (37, 'Post Merge Source');
INSERT INTO postHistoryTypes (id, name) VALUES (38, 'Post Merge Destination ');
